# @package _global_

# this config file is used for running the template default tests

defaults:
  - _self_
  - datamodule: mnist.yaml # choose datamodule with `test_dataloader()` for evaluation
  - module: mnist.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"
predict: False

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
